### ISSUE TITLE
examples for training and testing

### ISSUE THREAD

**Issue by ppengtang** [antran89/my-very-deep-caffe#1]
Hello, could you give some examples for training and testing two-stream CNN? Thank you very much!

**Comment by antran89** [comment]
@hust-tp Sorry for not noticing your messages. I will post some documents for training and testing two-stream CNN when I have time. Now this repo is not for my experiments. 
Hope to catch you all your requirements.

**Comment by ppengtang** [comment]
Thank you! I have found another source for training and testing two-stream CNN. So maybe you needn't waste your time for it.

**Comment by vra** [comment]
@ppengtang Hi, can you share your founded source repo of two-stream CNN? Thanks!

**Comment by ghost** [comment]
> Thank you! I have found another source for training and testing two-stream CNN. So maybe you needn't waste your time for it.

@ppengtang 
Which one did you find , Can you share your code's link with me , It really really helps me ,Thanks a lot
