### ISSUE TITLE
training on flow data

### ISSUE THREAD

**Issue by tonmoy-saikia** [antran89/my-very-deep-caffe#2]
Hi @antran89, Have you tried training the temporal net? 
I am currently using the VGG-2048 model, but the data loading is too slow from the file system.
Have you tried lmdb?

**Comment by antran89** [comment]
@tonmoy-saikia 
Sorry, I did not notice your message. My mailbox is in mess from BLVC Caffe messages. Yeah, indeed, it is very slow to load optical flow images from disk. That is why I develop LDMB interfaces to work with the video classification problem using CNN. Right now, I do not have detailed documentations and examples for my implementation. I will try have some documents and examples soon.
In the mean time, you can use the [tool](https://github.com/antran89/my-very-deep-caffe/blob/master/tools/convert_segment_flow.cpp) converting video optical flow into LDMB database. And use two-stream CNN models that leverage LMDB interface.
I will update the README as soon as I finish all the testing and documentations. Now, the interface is working fine.

**Comment by tonmoy-saikia** [comment]
@antran89 Looks good. But does it mean you will have database of each stack_size? What is the size of a lmdb database for UCF flow data (if you have already dumped it)? I am using an SSD drive, works okayish.

**Comment by antran89** [comment]
@tonmoy-saikia Sorry for late reply again.
I already dump it database for testing several network architecture. The rgb & flow database is 16.8GB and flow database is 105.6GB. It is quite manageable with current hardware. The trick (also different from Wang's implementation) is to reduce the resolution of video into smaller resolution, e.g.,  (128, 171) to reduce spaces. I observed that it does not reduce performances so much.

**Comment by antran89** [comment]
Hi @tonmoy-saikia,
Sorry for late reply, I just finished releasing trained CAFFE model at https://github.com/antran89/two-stream-fcan.
Please take a look.
